CREATE TABLE Kategorie (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nazwa NVARCHAR(255) NOT NULL
);

CREATE TABLE Czesci (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nazwa NVARCHAR(255) NOT NULL,
	NrKatalogowy NVARCHAR(255) NOT NULL,
	KategoriaId INT NOT NULL,
	Cena DECIMAL(18, 2) NOT NULL,
	StanMagazynowy INT NOT NULL,

	CONSTRAINT FK_Czesci_Kategorie FOREIGN KEY (KategoriaId) REFERENCES Kategorie(Id),
	CHECK (StanMagazynowy >= 0 AND Cena >= 0)
);

CREATE TABLE Klienci(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	NazwaFirmy NVARCHAR(255) NOT NULL,
	NIP NVARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE Zamowienia (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	DataZamowienia DATETIME NOT NULL DEFAULT GETDATE(),
	KlientId INT NOT NULL,
	FOREIGN KEY (KlientId) REFERENCES Klienci(Id)
);

CREATE TABLE PozycjeZamowienia (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	ZamowienieId INT NOT NULL,
	CzescId INT NOT NULL,
	Ilosc INT NOT NULL,
	CenaJednostkowa DECIMAL(18, 2) NOT NULL,
	FOREIGN KEY (ZamowienieId) REFERENCES Zamowienia(Id),
	FOREIGN KEY (CzescId) REFERENCES Czesci(Id)
);