CREATE DATABASE CarPartsStore;
GO

USE CarPartsStore;
GO

CREATE TABLE Categories (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL
);
GO

CREATE TABLE Parts (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
	CatalogNumber NVARCHAR(255) NOT NULL,
	CategoryId INT NOT NULL,
	Price DECIMAL(18, 2) NOT NULL,
	StockQuantity INT NOT NULL,

	CONSTRAINT FK_Parts_Categories FOREIGN KEY (CategoryId) REFERENCES Categories(Id),
	CHECK (StockQuantity >= 0 AND Price >= 0)
);
GO

CREATE TABLE Customers(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	CompanyName NVARCHAR(255) NOT NULL,
	NIP NVARCHAR(20) UNIQUE NOT NULL
);
GO

CREATE TABLE Orders (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	OrderDate DATETIME NOT NULL DEFAULT GETDATE(),
	CustomerId INT NOT NULL,
	FOREIGN KEY (CustomerId) REFERENCES Customers(Id)
);
GO

CREATE TABLE OrderItems (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	OrderId INT NOT NULL,
	PartId INT NOT NULL,
	Quantity INT NOT NULL,
	UnitPrice DECIMAL(18, 2) NOT NULL,
	FOREIGN KEY (OrderId) REFERENCES Orders(Id),
	FOREIGN KEY (PartId) REFERENCES Parts(Id)
);
GO